# Generated by Django 4.1.3 on 2022-11-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarity',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
